language: python
sudo: true

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-ansible23
    - python: 2.7
      env: TOXENV=py27-ansible22
    - python: 2.7
      env: TOXENV=py27-ansible21
    - python: 2.7
      env: TOXENV=py27-ansible20
    - python: 2.7
      env: TOXENV=py27-ansible19

install:
  - pip install tox

script:
  - tox

notifications:
  email: false
  slack:
    template:
      - "%{repository_name}@%{branch} %{commit} : [%{build_number}] %{result} "
      - "%{build_url}"
      - "'%{commit_subject}' by %{author}"
      - "%{elapsed_time} : %{duration}"
      - "%{message}"
    on_success: always
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

before_cache:
  - "find ${HOME}/.pip -name log -o -name __pycache__ -type d | xargs -I {} rm -rf {}"

cache:
  directories:
    - "${HOME}/.cache/pip"
